hobbysite/blog/urls.py
from django.urls import path
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from .views import (
    ArticleListView,
    ArticleDetailView,
    ArticleCreateView,
    ArticleUpdateView,
)

app_name = "blog"

urlpatterns = [
    path("", lambda request: HttpResponseRedirect(reverse_lazy("blog:article-list"))),
    path("articles/", ArticleListView.as_view(), name="article-list"),
    path("article/add/", ArticleCreateView.as_view(), name="article-create"),
    path("article/<int:pk>/", ArticleDetailView.as_view(), name="article-detail"),
    path("article/<int:pk>/edit/", ArticleUpdateView.as_view(), name="article-edit"),
]

hobbysite/hobbysite/urls.py
from django.contrib import admin
from django.urls import path, include
from user_management.views import home_view

from django.conf import settings  # ➔ add
from django.conf.urls.static import static  # ➔ add

urlpatterns = [
    path("admin/", admin.site.urls),

    # Core apps
    path("forum/", include("forum.urls")),
    path("commissions/", include("commissions.urls")),
    path("blog/", include("blog.urls")),
    path("wiki/", include("wiki.urls")),
    path("merchstore/", include("merchstore.urls")),

    # Authentication (Login, Logout, Password)
    path("accounts/", include("django.contrib.auth.urls")),

    # User management (registration, profile, etc.)
    path("accounts/", include("user_management.urls")),

    # Root route redirects to the custom homepage
    path("", home_view, name="home"),
]

# ➔ serve media files (uploads) during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hobbysite/merchstore/urls.py
from django.urls import path
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from .views import (
    ProductListView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    CartView,
    TransactionListView
    )

app_name = "merchstore"

urlpatterns = [
    path("", lambda request: HttpResponseRedirect(reverse_lazy("merchstore:product-list"))),
    path("items", ProductListView.as_view(), name='product-list'),
    path("item/<int:pk>", ProductDetailView.as_view(), name='product-detail'),
    path("item/add", ProductCreateView.as_view(success_url=reverse_lazy('merchstore:product-list')), name='product-create'),
    path("item/<int:pk>/edit", ProductUpdateView.as_view(success_url=reverse_lazy('merchstore:product-list')), name='product-edit'),
    path("cart", CartView.as_view(), name='cart-list'),
    path("transactions", TransactionListView.as_view(), name='transaction-list')
]

hobbysite/merchstore/models.py
from django.db import models
from user_management.models import Profile

class ProductType(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    class Meta:
        ordering = ['name']

class Product(models.Model):
    STATUS_CHOICES = {'Available':'Available', 
        'On sale':'On sale', 
        'Out of stock':'Out of stock'}

    name = models.CharField(max_length=255)
    product_type = models.ForeignKey(ProductType, null=True, on_delete=models.SET_NULL)
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL, related_name="product")
    description = models.TextField()
    price = models.DecimalField(max_digits=99, decimal_places=2)
    stock = models.IntegerField()
    status = models.CharField(max_length=255, default="Available", choices=STATUS_CHOICES)

    def save(self, *args, **kwargs):
        if self.stock <= 0:
            self.status = "Out of stock"
        super(Product, self).save(*args, **kwargs)

    class Meta:
        ordering = ['name']

class Transaction(models.Model):
    buyer = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL, related_name="transaction")
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL, related_name="transaction")
    amount = models.IntegerField()
    status = models.CharField(max_length=255, default="On cart")
    created_on = models.DateTimeField(auto_now_add=True)

hobbysite/merchstore/forms.py
from django import forms
from .models import Product, Transaction

class ProductForm(forms.ModelForm):
	class Meta:
		model = Product
		def get_product_type_names():
			names = dict()
			for type in Product.objects.values_list('product_type', flat=true).distinct():
				names[type] = type.name 
			return names
		fields = ['name', 'product_type', 'description', 'price', 'stock', 'status']
		widgets = {
			'name': forms.TextInput(attrs={'class': 'form-control'}),
			'product_type': forms.Select(choices=get_product_type_names, attrs={'class': 'form-control'}),
			'description': forms.TextInput(attrs={'class': 'form-control', 'rows': 5}),
			'price': forms.NumberInput(attrs={'class': 'form-control'}),
			'stock': forms.NumberInput(attrs={'class': 'form-control'}),
			'status': forms.Select(attrs={'class': 'form-control'})
		}

class TransactionForm(forms.ModelForm):
	class Meta:
		model = Transaction
		fields = ['amount']
		widgets = {
			'amount': forms.NumberInput(attrs={'class': 'form-control'}),
		}

hobbysite/merchstore/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.shortcuts import get_object_or_404, redirect
from .models import ProductType, Product, Transaction
from .forms import TransactionForm
from user_management.models import Profile

class ProductListView(ListView):
	model = Product
	template_name = 'product_list.html'
	context_object_name = 'products'


class ProductDetailView(DetailView):
	model = Product
	template_name = 'product_detail.html'
	context_object_name= 'product'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		product = self.get_object()
		context['transaction_form'] = TransactionForm()

		return context

	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return redirect("login")

		self.object = self.get_object()
		profile = get_object_or_404(Profile, user=request.user)
		form = TransactionForm(request.POST)

		if form.is_valid():
			transaction = form.save(commit=False)
			transaction.buyer = profile
			transaction.product = self.object
			transaction.save()
			return redirect("merchstore:cart-list")

		context = self.get_context_data()
		context["transaction_form"] = form
		return self.render_to_response(context)


class ProductCreateView(LoginRequiredMixin, CreateView):
	model = Product
	template_name = 'product_form.html'
	fields = ['name', 'product_type', 'description', 'price', 'stock', 'status']

	def form_valid(self, form):
		form.instance.owner = get_object_or_404(Profile, user=self.request.user)
		return super().form_valid(form)



class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Product
	template_name = 'product_form.html'
	fields = ['name', 'product_type', 'description', 'price', 'stock', 'status']

	def test_func(self):
		product = self.get_object()
		return product.owner.user == self.request.user


class CartView(LoginRequiredMixin, ListView):
	model = Transaction
	template_name = 'cart_list.html'
	context_object_name = 'cart'

	def get_queryset(self):
		return Transaction.objects.filter(buyer__user__exact=self.request.user)


class TransactionListView(LoginRequiredMixin, ListView):
	model = Transaction
	template_name = 'transaction_list.html'
	context_object_name = 'transactions'

	def get_queryset(self):
		return Transaction.objects.filter(product__owner__user__exact=self.request.user)

hobbysite/merchstore/templates/cart_list.html
{% extends "base.html" %}

{% block title %}
	Cart View
{% endblock %}

{% block content %}

	<h2>Cart View</h2>
	<ul class="cart-list">
		{% for transaction in cart %}
			<li class="product-item">
				<h4>
					<a href="{% url 'merchstore:product-detail' transaction.product.pk}">
						{{ transaction.product.name }}
					</a>
				</h4>
				<p><b>{{ transaction.product.product_type }}</b></p>
				<p>Description: {{ transaction.product.description }}</p>
				<p>Price: {{ transaction.product.price }}</p>
				<p>Amount: {{ transaction.amount }}</p>
				<p>Status: {{ transaction.status }}</p>
			</li>
		{% endfor %}
	</ul>

{% endblock %}

hobbysite/merchstore/templates/merchstore_detail.html
<!DOCTYPE hmtl>

<html>
	<head>
		<title>Merchandise Store</title>
	</head>

	<body>
		<header>
			<h1>Merchandise Store</h1>
		</header>
		<h2>{{ product_type.name }}</h2>
		<p>{{ product_type.description }}</p>
		<ul>
			{% for item in product %}
			<li><b>{{ item.name }}</b></li>
			<p>Description: {{ item.description }}</p>
			<p>Price: {{ item.price }}</p>
			{% endfor %}
		</ul>

	</body>
</html>

hobbysite/merchstore/templates/merchstore_list.html
<!DOCTYPE hmtl>

<html>
	<head>
		<title>Merchandise Store</title>
	</head>

	<body>
		<header>
			<h1>Merchandise Store</h1>
		</header>
		<ul>
			{% for item in product_type %}
			<li><a href="/merchstore/item/{{item.id}}">{{ item.name }}</a></li>
			<p>Description: {{ item.description }}</p>
			{% endfor %}
		</ul>

	</body>
</html>

hobbysite/merchstore/templates/product_detail.html
{% extends "base.html" %}

{% block title %}
Merchstore
{% endblock %}

{% block content %}
<h2>Product Detail</h2>

<h3>{{ product.name }}</h3>
<p><b>{{ product.product_category.name }}</b></p>
<p>Stock: {{ product.stock }}</p>
<p>{{ product.description }}</p>

{% if user.is_authenticated %}
	{% if user != product.owner.user %}
		<form method="post">
			{% csrf_token %}
			{% if transaction_form.errors %}
				<div style="color:red">
					Please fix the errors below.
				</div>
			{% endif %}
			<div>
				{{ transaction_form.amount.label_tag }}
				{{ transaction_form.amount }}
				{% if transaction_form.amount.errors %}
					<div style="color:red">{{ transaction_form.amount.errors }}</div>
				{% endif %}
			</div>
			{% if product.stock <= 0 %}
				<button type="submit" disabled>Buy</button>
			{% else %}
				<button type="submit">Buy</button>
			{% endif %}	
		</form>
	{% else %}
		<p><a href="{% url 'merchstore:product-edit' product.pk %}">Edit Product</a></p>
	{% endif %}
{% else %}
<p><a href="{% url 'login' %}">Login</a> to buy this product</p>
{% endif %}

{% endblock %}

hobbysite/merchstore/templates/product_form.html
{% extends "base.html" %}

{% block title %}
	{% if form.instance.pk %}
		Edit Product
	{% else %}
		New Product
	{% endif %}
{% endblock %}

{% block content %}
	<h2>
		{% if form.instance.pk %}
			Edit Product
		{% else %}
			New Product
		{% endif %}
	</h2>

	<form method="post" enctype="multipart/form_date" class="thread-form">
		{% csrf_token %}
		{{ form.non_field_errors }}

		{% for field in form %}
			<div class="form-group">
				{{ field.label_tag }}
				{{ field }}
				{{ field.errors }}
			</div>
		{% endfor %}

		<button type="submit" class="btn btn-primary">
			Submit
		</button>
	</form>

	<p><a href="{% url 'merchstore:product-list' %}">Back to Product list</a><p>
{% endblock %}

hobbysite/merchstore/templates/product_list.html
{% extends "base.html" %}

{% block title %}
Merchstore
{% endblock %}

{% block content %}
<h2>Product List</h2>

{% if user.is_authenticated %}

{% if products %}
	<h3>Your Products</h3>
	<ul class="product-list">
		{% for product in products %}
			{% if user == product.owner.user %}
				<li class="product-item">
					<h4>
						<a href="{% url 'merchstore:product-detail' product.pk %}">
							{{ product.name }}
						</a>
					</h4>
					<p><b>{{ product.product_type.name }}</b></p>
					<p>Owner: {{ product.owner }}</p>
					<p>Description: {{ product.description }}</p>
					<p>Price: {{ product.price }}</p>
					<p>Stock: {{ product.stock }}</p>
					<p>Status: {{ product.status }}</p>
				</li>
			{% endif %}
		{% endfor %}
	</ul>
	<h3>Other Users' Products</h3>
	<ul class="product-list">
		{% for product in products %}
			{% if user != product.owner.user %}
				<li class="product-item">
					<h4>
						<a href="{% url 'merchstore:product-detail' product.pk %}">
							{{ product.name }}
						</a>
					</h4>
					<p><b>{{ product.product_type }}</b></p>
					<p>Owner: {{ product.owner }}</p>
					<p>Description: {{ product.description }}</p>
					<p>Price: {{ product.price }}</p>
					<p>Stock: {{ product.stock }}</p>
					<p>Status: {{ product.status }}</p>
				</li>
			{% endif %}
		{% endfor %}
	</ul>
{% else %}
	<p>No products yet. Be the first to place a product in the market!</p>
{% endif %}

<p><a href="{% url 'merchstore:product-create' %}">Place a Product</a></p>

{% else %}

{% if products %}
	<ul class="product-list">
		{% for product in products %}
			<li class="product-item">
				<h4>
					<a href="{% url 'merchstore:product-detail' product.pk %}">
						{{ product.name }}
					</a>
				</h4>
				<p><b>{{ product.product_type }}</b></p>
				<p>Owner: {{ product.owner }}</p>
				<p>Description: {{ product.description }}</p>
				<p>Price: {{ product.price }}</p>
				<p>Stock: {{ product.stock }}</p>
				<p>Status: {{ product.status }}</p>
			</li>
		{% endfor %}
	</ul>
{% else %}
	<p>No products yet. Be the first to place a product in the market!</p>
{% endif %}

{% endif %}

{% endblock %}

hobbysite/merchstore/templates/transaction_list.html
{% extends "base.html" %}

{% block title %}
	Transaction View
{% endblock %}

{% block content %}

	<h2>Transaction View</h2>
	<ul class="cart-list">
		{% for transaction in transactions %}
			<li class="product-item">
				<h4>
					<a href="{% url 'merchstore:product-detail' transaction.product.pk}">
						{{ transaction.product.name }}
					</a>
				</h4>
				<p><b>{{ transaction.product.product_type }}</b></p>
				<p>Description: {{ transaction.product.description }}</p>
				<p>Price: {{ transaction.product.price }}</p>
				<p>Buyer: {{ transaction.buyer }}</p>
				<p>Amount: {{ transaction.amount }}</p>
				<p>Status: {{ transaction.status }}</p>
			</li>
		{% endfor %}
	</ul>

{% endblock %}